console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
terminal_background = 'p:t-background'
version = 3
final_space = true

[palette]
light-sky-blue = '#6cbfbf'
main-bg = '#232a2d'
pistachio-green = '#8ccf7e'
t-background = 'p:main-bg'
terminal-blue = '#67b0e8'
terminal-magenta = '#c47fd5'
terminal-red = '#e57474'
terminal-yellow = '#e5c76b'

[secondary_prompt]
template = '➜ '
foreground = 'p:terminal-blue'
background = 'transparent'

[transient_prompt]
template = '{{ if .Env.container }}(󰏖 {{ .Env.container | title }}) {{end}}➜ '
foreground = "p:terminal-red"
foreground_templates = [
  '{{ if eq .Code 0 }}p:terminal-blue{{ end }}',
]
background = 'transparent'

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = '{{if not .Writable}}<p:terminal-red></>{{else}}{{end}} <b>{{ .Path }} </b>'
foreground = 'p:light-sky-blue'
type = 'path'
style = 'plain'

  [blocks.segments.properties]
style = 'powerlevel'
max_width = 25

[[blocks.segments]]
template = '({{ .HEAD}})'
foreground = 'p:terminal-yellow'
type = 'git'
style = 'plain'

  [blocks.segments.properties]
branch_icon = ' '
fetch_status = false

[[blocks]]
type = 'prompt'
alignment = 'right'
overflow = 'hide'

[[blocks.segments]]
template = ' {{ .Full }} '
foreground = 'p:pistachio-green'
type = 'node'
style = 'plain'

[[blocks.segments]]
template = ' {{ .Full }}{{if .Venv}} ({{ .Venv }}){{end}} '
foreground = 'p:terminal-yellow'
type = 'python'
style = 'plain'

[[blocks.segments]]
template = ' {{ .Full }} '
foreground = 'p:light-sky-blue'
type = 'go'
style = 'plain'

[[blocks.segments]]
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '
type = 'rust'
style = 'plain'
foreground = 'p:terminal-red'

[[blocks.segments]]
template = '󰦖 took {{ .FormattedMs }}'
foreground = 'p:terminal-yellow'
style = 'plain'
type = 'executiontime'
  [blocks.segments.properties]
threshold = 500
style = 'round'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = "p:terminal-red"
foreground_templates = [
  '{{ if eq .Code 0 }}p:terminal-blue{{ end }}',
]
template = '{{ if .Env.container }}(󰏖 {{ .Env.container | title }}) {{end}}'

  [blocks.segments.properties]
fetch_version = false

[[blocks.segments]]
template = '➜'
foreground = "p:terminal-red"
foreground_templates = [
  '{{ if eq .Code 0 }}p:terminal-blue{{ end }}',
]
type = 'text'
style = 'plain'
